language: scala
scala:
- 2.11.4
jdk:
- openjdk7
sudo: false
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
script: sbt ++$TRAVIS_SCALA_VERSION test ; result=$? ; find $HOME/.sbt -name "*.lock" -type f -delete ; find $HOME/.ivy2/cache -name "*[\[\]\(\)]*.properties" -type f -delete ; (exit $result)
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt stage deployHeroku
env:
  global:
  - secure: ay2NiHHNKZ+RvVe/IafJNkJHIDAPB9DKHrbZKJaGc913xdSXvD2K/0JU7RXGgrP0M3mhsztuR3sNlEDm7qDWFIa760YAmAT9yi/QQ25CLyQ7z0xUl5GdT5X6LqoAkQhVlkxYVW4AFGjLMOQaXGLM0Tck0JggMGjE0YhoXMlca20=
  - secure: icDyL7Jc++vYYqWA9OdJciwr558V9PLdZz0NaN+zpyRPiIDfv8NLBMEaQV5CZ0WY9fuw0BhSlwQQFG3oIAY4O/9OKy8X6X25MZtKVCT7dFgEC1qpTl3rXB2049a5YbOfLYeUMtXmGvmDEtqm0acKVw2zl3DGXNryBVBZEEUfb7M=
